#:schema node_modules/wrangler/config-schema.json
name = "caproweb"

main = "./server.ts"

workers_dev = true
compatibility_date = "2024-12-30"
compatibility_flags = [ "nodejs_compat" ]

assets = { directory = "./build/client" }

[vars]
ENVIRONMENT = "production"

[observability]
enabled = true
head_sampling_rate = 0.1
