name: Deps Auto Merge
on: pull_request
jobs:
  merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - id: meta
        uses: dependabot/fetch-metadata@v2
      - if: >-
          ${{ 
            steps.meta.outputs.update-type == 'version-update:semver-patch' ||
            (
              steps.meta.outputs.dependency-type == 'direct:development' &&
              steps.meta.outputs.update-type != 'version-update:semver-major'
            ) ||
            (
              steps.meta.outputs.package-ecosystem == 'github-actions' &&
              steps.meta.outputs.update-type != 'version-update:semver-major'
            )
          }}
        run: |
          gh pr review "${{ github.head_ref }}" --approve
          gh pr merge "${{ github.head_ref }}" --merge --auto
